name: release

on:
  push:
    tags:
      - "fips-*" # see: https://github.com/envoyproxy/envoy/blob/73dc561f0c227c03ec6535eaf4c30d16766236a0/bazel/repository_locations.bzl#L140C20-L140C33.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - amd64
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - name: Run builder
        run: make
        env:
          TAG: ${{ github.ref_name || github.ref }}
          ARCH: ${{ matrix.arch }}
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          path: boringssl-fips-${{ env.TAG }}-${{ matrix.arch }}.tar.xz
          name: boringssl-fips-${{ matrix.arch }}
        env:
          TAG: ${{ github.ref_name || github.ref }}

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      - uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          tag_name: ${{ github.ref_name || github.ref }}
          generate_release_notes: true
          files: |
            boringssl-fips-amd64/**/*.tar.xz
            boringssl-fips-arm64/**/*.tar.xz
