name: release

on:
  push:
    tags:
      - "fips-*" # see: https://github.com/envoyproxy/envoy/blob/73dc561f0c227c03ec6535eaf4c30d16766236a0/bazel/repository_locations.bzl#L140C20-L140C33.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - amd64
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
      - uses: docker/setup-buildx-action@885d1462b80bc1c1c7f0b00334ad271f09369c55 # v2.10.0
      - name: Run builder
        run: make
        env:
          TAG: ${{ github.ref_name || github.ref }}
          ARCH: ${{ matrix.arch }}
      - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # v2.3.1
        with:
          path: boringssl-fips-${{ env.TAG }}-${{ matrix.arch }}.tar.xz
          name: boringssl-fips-${{ matrix.arch }}
        env:
          TAG: ${{ github.ref_name || github.ref }}

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@f023be2c48cc18debc3bacd34cb396e0295e2869 # v2.1.0
      - uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
        with:
          tag_name: ${{ github.ref_name || github.ref }}
          generate_release_notes: true
          files: |
            boringssl-fips-amd64/**/*.tar.xz
            boringssl-fips-arm64/**/*.tar.xz
